site: ankarenko.live
url: https://ankarenko.live
title: Ankarenko.live
description: про путешествия и не только.
author:
  alltrails: https://www.alltrails.com/members/sergey-ankarenko?ref=header
  github: https://github.com/ankarenko
  vk: https://vk.com/ankarenko
  name: Sergei Ankarenko
  avatar: /me.png
  email: #youremail
github:
  url: https://github.com/ankarenko/blog
permalink: pretty

baseurl: ""

highlighter: none


exclude:
  - .jekyll-cache
  
compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]

sass:
  sass_dir:          _sass
  style:            :compressed

plugins:
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-sitemap

collections:
  pages:
    output: true
    permalink: /:path
  posts:
    output: true
    permalink: /:year-:month-:day-:slug
  
defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
      images_root_path: "/assets/images"
      sizes: 
        - width: 1100
          size: "lg"
        - width: 800
          size: "md"
        - width: 420
          size: "sm"
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"