name: Build and Deploy to Github Pages

on:
  push:
    branches:
      - master  # Here source code branch is `master`, it could be other branch

env:
  IMAGE_DIRECTORY: '${PWD}/assets/images'

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    
    permissions: write-all
      
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0  # OR "2" -> To retrieve the preceding commit.
          lfs: 'true'
 
      # Use GitHub Actions' cache to cache dependencies on servers
      - uses: actions/cache@v3
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gems-


    shell: bash
      - name: Get Date
        id: get-date
        run: |
          echo "date=$(/bin/date -u "+%Y%m%d")" >> $GITHUB_OUTPUT

      - uses: actions/cache@v3
        with:
          path: assets/images/resized
          key: ${{ runner.os }}-images-resized-${{ steps.get-date.outputs.date }}
          restore-keys: ${{ runner.os }}-images-resized #?

      - name: Generating resized images
        run: ./make.sh
        shell: bash

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v35
        with:
          since_last_remote_commit: "true"
          files: assets/images/**/*.jpg  
      
      - name: Run step if any *.jpg changed
        if: steps.changed-files.outputs.any_changed == 'true' 
        run: |
          for file in ${{ steps.changed-files.outputs.modified_files }}; do
            echo "$file was changed, processing..."
            source ./gen_resized.sh $file
          done
        shell: bash

